"""create ingestion_batches, departments, jobs, employees tables

Revision ID: baf15e3018b0
Revises: 
Create Date: 2026-07-01 16:47:03.273653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf15e3018b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique batch identifier'),
    sa.Column('status', sa.Enum('pending', 'completed', name='ingestion_batch_status'), nullable=False, comment='Ingestion status'),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Row-level errors collected during ingestion'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the batch was created'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks each CSV ingestion request for audit and traceability'
    )
    op.create_index('ix_ingestion_batches_id', 'ingestion_batches', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('batch_id', sa.UUID(), nullable=False, comment='Ingestion batch this row belongs to'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Id of the department'),
    sa.Column('department', sa.String(), nullable=False, comment='Name of the department'),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Company departments'
    )
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('batch_id', sa.UUID(), nullable=False, comment='Ingestion batch this row belongs to'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Id of the job'),
    sa.Column('job', sa.String(), nullable=False, comment='Name of the job position'),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Available job positions'
    )
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp'),
    sa.Column('batch_id', sa.UUID(), nullable=False, comment='Ingestion batch this row belongs to'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Id of the employee'),
    sa.Column('name', sa.String(), nullable=False, comment='Name and surname of the employee'),
    sa.Column('hiring_datetime', sa.DateTime(timezone=True), nullable=False, comment='Hire datetime in ISO format'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='Id of the department which the employee was hired for'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='Id of the job which the employee was hired for'),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Historical hired employees'
    )
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_ingestion_batches_id', table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    # ### end Alembic commands ###
