name: Run test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  
jobs:
  run-ci:
    runs-on: ubuntu-latest
    env:
        PYTHONPATH: hiring-service/src
    defaults:
      run:
        working-directory: hiring-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
      
      - name: Sync dependencies
        run: uv sync --extra dev
      
      - name: Run unit test
        run: uv run pytest tests/unit
      
      - name: Run integration test
        timeout-minutes: 10
        run: uv run pytest tests/integration
